include "math.lix";
include "util.lix";

function test_async() {
    for (i = 1; i <= 5; i++) {
        println("Hello from a different thread! (x" + i + ")");
    }
}

function main() {
	/*
    async(this::test_async);
    EXECUTOR_SERVICE.shutdown();

    n = 5;
    println("Factorial " + n + " = " + factorial_r(n));
    */

    a = "000";
    a = null;

    try println(a = a.replace('0', '1'));
    catch (e) println("Exception handled: " + e);
}
